name: counter_app
description: Example app for reduced_riverpod.
publish_to: 'none' 
version: 0.4.1+6

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
#  reduced: 0.4.1
  reduced: 
    git:
      url: https://github.com/partmaster/reduced.git
      ref: v0.4.1-beta.4
  flutter_riverpod: ^2.2.0
  reduced_riverpod: 
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
